### ISSUE TITLE
Ergast integration tracking

### ISSUE THREAD

**Issue by Loafabreadly** [Loafabreadly/F1Discord-Bot#4]
- [X] F1 race [year] [race number] - `/race [season] [race number]`
- [ ] F1 driver [name]
- [ ] F1 track [track]
- [ ] F1 qualipreview 
- [ ] F1 racepreview
- [x] Current Standings - `/standings [driver, constructor, both]` Also accepts "d", "c", "b".
- [x] Circuit info
- [ ] Pit stops info
- [ ] Lap times
- [X] Constructor info - `/constructors [constructorId]` Replace Spaces with _ (red_bull), engine works teams are denoted by a hyphen (brabham-brm)
- [ ] Season info

**Comment by Loafabreadly** [comment]
- [x] Current Standings - `/standings [driver, constructor, both]` Also accepts "d", "c", "b".
- [ ] Circuit info
- [ ] Pit stops info
- [ ] Lap times
- [X] Constructor info - `/constructors [constructorId]` Replace Spaces with _ (red_bull), engine works teams are denoted by a hyphen (brabham-brm)
- [ ] Season info

**Comment by Loafabreadly** [comment]
CircuitInfo cmd in stg

**Comment by Loafabreadly** [comment]
Circuit Info, List Circuits, and List Constructors all pushed to main
